export const mockDoctors = [
  {
    id: 'd1',
    name: 'Dr. Ananya Rao',
    phone: '9876500001',
    specialization: 'Cardiologist',
    experience: 12,
    fee: 900,
    rating: 4.9,
    languages: ['English', 'Hindi'],
    city: 'Bengaluru',
    availability: ['Mon 10:00', 'Tue 12:30', 'Wed 17:00', 'Fri 09:30', 'Sat 14:00', 'Sun 11:30'],
  },
  {
    id: 'd2',
    name: 'Dr. Vikram Sen',
    phone: '9876500002',
    specialization: 'Dermatologist',
    experience: 8,
    fee: 650,
    rating: 4.8,
    languages: ['English', 'Bengali'],
    city: 'Kolkata',
    availability: ['Mon 09:30', 'Tue 14:00', 'Thu 18:00', 'Fri 11:30', 'Sat 16:00'],
  },
  {
    id: 'd3',
    name: 'Dr. Meera Iyer',
    phone: '9876500003',
    specialization: 'Psychiatrist',
    experience: 10,
    fee: 1200,
    rating: 4.7,
    languages: ['English', 'Tamil', 'Hindi'],
    city: 'Chennai',
    availability: ['Tue 10:30', 'Wed 13:00', 'Thu 17:30', 'Sat 09:00', 'Sun 15:30'],
  },
];

export const appointments = [
  {
    id: 1,
    doctor: 'Dr. Ananya Rao',
    date: 'Today, 4:30 PM',
    status: 'Confirmed',
    consultationId: 'consult-1',
    paymentAmount: 900,
    paymentStatus: 'paid',
    canJoin: true,
    mode: 'scheduled',
  },
  {
    id: 2,
    doctor: 'Dr. Vikram Sen',
    date: 'Tomorrow, 11:00 AM',
    status: 'Pending',
    consultationId: 'consult-2',
    paymentAmount: 650,
    paymentStatus: 'pending',
    canJoin: false,
    mode: 'scheduled',
  },
  {
    id: 3,
    doctor: 'Dr. Meera Iyer',
    date: '28 Mar, 9:30 AM',
    status: 'Completed',
    consultationId: 'consult-3',
    paymentAmount: 1200,
    paymentStatus: 'paid',
    canJoin: false,
    mode: 'scheduled',
  },
];

export const notifications = [
  { audience: 'patient', type: 'appointment', title: 'Appointment confirmed', description: 'Your consultation with Dr. Ananya Rao is booked for today at 4:30 PM.' },
  { audience: 'patient', type: 'prescription', title: 'New prescription ready', description: 'A dermatologist prescription has been uploaded to your records.' },
  { audience: 'patient', type: 'reminder', title: 'Medicine reminder', description: 'Take your evening dose at 8:00 PM after food.' },
  { audience: 'patient', type: 'tip', title: 'Health tip', description: 'Drink enough water and monitor your sleep this week.' },
  { audience: 'doctor', type: 'request', title: 'New appointment request', description: 'Rahul Mehta requested an online consultation for 6:30 PM.' },
  { audience: 'doctor', type: 'cancel', title: 'Appointment cancelled', description: 'Nisha Singh cancelled the 3:00 PM slot for today.' },
  { audience: 'doctor', type: 'message', title: 'New patient message', description: 'Aman Patel sent a follow-up message about post-visit symptoms.' },
  { audience: 'doctor', type: 'payment', title: 'Payment received', description: 'Consultation payment of Rs. 900 has been credited.' },
  { audience: 'doctor', type: 'reminder', title: 'Schedule reminder', description: 'You have 2 confirmed consultations in the next hour.' },
  { audience: 'doctor', type: 'system', title: 'System alert', description: 'Video service maintenance is scheduled for Sunday at 2:00 AM.' },
];
