export const chemistDummyInventory = [
  { _id: 'dm-001', name: 'Paracetamol 650', category: 'Painkiller', composition: 'Paracetamol', dosage: '1 tablet after food', batchNumber: 'PCM650-A11', supplierName: 'Sun Pharma Dist.', purchasePrice: 22, sellingPrice: 36, stockQuantity: 140, lowStockThreshold: 20, expiryDate: '2027-02-15', isPublicVisible: true, availabilityStatus: 'available', description: 'Fever and pain relief', usageInstructions: 'Max 3 tablets/day', isPrescriptionRequired: false },
  { _id: 'dm-002', name: 'Dolo 650', category: 'Painkiller', composition: 'Paracetamol', dosage: '1 tablet as needed', batchNumber: 'DLO650-B21', supplierName: 'Micro Labs', purchasePrice: 24, sellingPrice: 38, stockQuantity: 80, lowStockThreshold: 25, expiryDate: '2026-12-10', isPublicVisible: true, availabilityStatus: 'available', description: 'Pain and fever', usageInstructions: 'Take with water', isPrescriptionRequired: false },
  { _id: 'dm-003', name: 'Crocin Advance', category: 'Painkiller', composition: 'Paracetamol', dosage: '1 tablet every 8 hours', batchNumber: 'CRC-ADV-88', supplierName: 'GSK Supply', purchasePrice: 26, sellingPrice: 42, stockQuantity: 0, lowStockThreshold: 18, expiryDate: '2026-11-01', isPublicVisible: true, availabilityStatus: 'out_of_stock', description: 'Fast fever relief', usageInstructions: 'Do not exceed 3/day', isPrescriptionRequired: false },
  { _id: 'dm-004', name: 'Azithromycin 500', category: 'Antibiotic', composition: 'Azithromycin', dosage: '1 tablet daily x 3 days', batchNumber: 'AZI500-C09', supplierName: 'Cipla', purchasePrice: 68, sellingPrice: 110, stockQuantity: 14, lowStockThreshold: 20, expiryDate: '2026-09-20', isPublicVisible: true, availabilityStatus: 'available', description: 'Bacterial infection support', usageInstructions: 'Doctor advice only', isPrescriptionRequired: true },
  { _id: 'dm-005', name: 'Amoxicillin 500', category: 'Antibiotic', composition: 'Amoxicillin', dosage: '1 capsule twice daily', batchNumber: 'AMX500-D44', supplierName: 'Mankind', purchasePrice: 74, sellingPrice: 122, stockQuantity: 35, lowStockThreshold: 20, expiryDate: '2026-05-18', isPublicVisible: true, availabilityStatus: 'available', description: 'Antibiotic capsule', usageInstructions: 'Complete full course', isPrescriptionRequired: true },
  { _id: 'dm-006', name: 'Cetirizine 10', category: 'Allergy', composition: 'Cetirizine', dosage: '1 tablet at night', batchNumber: 'CTZ10-E31', supplierName: 'Dr Reddy Dist.', purchasePrice: 12, sellingPrice: 25, stockQuantity: 170, lowStockThreshold: 30, expiryDate: '2027-03-11', isPublicVisible: true, availabilityStatus: 'available', description: 'Allergy and sneezing relief', usageInstructions: 'May cause drowsiness', isPrescriptionRequired: false },
  { _id: 'dm-007', name: 'Levocetirizine 5', category: 'Allergy', composition: 'Levocetirizine', dosage: '1 tablet daily', batchNumber: 'LCT5-E78', supplierName: 'Torrent', purchasePrice: 14, sellingPrice: 30, stockQuantity: 28, lowStockThreshold: 25, expiryDate: '2026-08-06', isPublicVisible: true, availabilityStatus: 'available', description: 'Advanced allergy support', usageInstructions: 'Prefer at bedtime', isPrescriptionRequired: false },
  { _id: 'dm-008', name: 'Pantoprazole 40', category: 'Gastro', composition: 'Pantoprazole', dosage: '1 tablet before breakfast', batchNumber: 'PAN40-F64', supplierName: 'Lupin', purchasePrice: 34, sellingPrice: 60, stockQuantity: 75, lowStockThreshold: 20, expiryDate: '2026-10-10', isPublicVisible: true, availabilityStatus: 'available', description: 'Acidity and reflux', usageInstructions: 'Take on empty stomach', isPrescriptionRequired: false },
  { _id: 'dm-009', name: 'Ranitidine 150', category: 'Gastro', composition: 'Ranitidine', dosage: '1 tablet twice daily', batchNumber: 'RAN150-F12', supplierName: 'Abbott Dist.', purchasePrice: 18, sellingPrice: 34, stockQuantity: 9, lowStockThreshold: 15, expiryDate: '2026-04-25', isPublicVisible: true, availabilityStatus: 'available', description: 'Acidity reduction', usageInstructions: 'As prescribed', isPrescriptionRequired: false },
  { _id: 'dm-010', name: 'ORS Sachet', category: 'Hydration', composition: 'ORS Salts', dosage: '1 sachet in 1L water', batchNumber: 'ORS-G55', supplierName: 'WHO Pharma Link', purchasePrice: 8, sellingPrice: 15, stockQuantity: 16, lowStockThreshold: 20, expiryDate: '2027-01-18', isPublicVisible: true, availabilityStatus: 'available', description: 'Hydration support', usageInstructions: 'Use clean water', isPrescriptionRequired: false },
  { _id: 'dm-011', name: 'Zinc 20 mg', category: 'Supplements', composition: 'Zinc Sulphate', dosage: '1 tablet daily', batchNumber: 'ZNC20-H22', supplierName: 'Apex Pharma', purchasePrice: 10, sellingPrice: 22, stockQuantity: 95, lowStockThreshold: 25, expiryDate: '2026-11-22', isPublicVisible: true, availabilityStatus: 'available', description: 'Immunity supplement', usageInstructions: 'Take after meal', isPrescriptionRequired: false },
  { _id: 'dm-012', name: 'Vitamin D3 60000', category: 'Supplements', composition: 'Cholecalciferol', dosage: '1 capsule weekly', batchNumber: 'VD3-I14', supplierName: 'Intas', purchasePrice: 24, sellingPrice: 48, stockQuantity: 46, lowStockThreshold: 15, expiryDate: '2026-07-30', isPublicVisible: true, availabilityStatus: 'available', description: 'Vitamin D deficiency support', usageInstructions: 'Once a week', isPrescriptionRequired: false },
  { _id: 'dm-013', name: 'Metformin 500', category: 'Diabetes', composition: 'Metformin', dosage: '1 tablet twice daily', batchNumber: 'MTF500-J39', supplierName: 'USV', purchasePrice: 28, sellingPrice: 54, stockQuantity: 62, lowStockThreshold: 20, expiryDate: '2026-12-05', isPublicVisible: true, availabilityStatus: 'available', description: 'Blood sugar management', usageInstructions: 'After food', isPrescriptionRequired: true },
  { _id: 'dm-014', name: 'Glimipride 1', category: 'Diabetes', composition: 'Glimipride', dosage: '1 tablet daily', batchNumber: 'GLM1-J60', supplierName: 'Alkem', purchasePrice: 22, sellingPrice: 44, stockQuantity: 12, lowStockThreshold: 18, expiryDate: '2026-06-15', isPublicVisible: true, availabilityStatus: 'available', description: 'Type-2 diabetes support', usageInstructions: 'As prescribed', isPrescriptionRequired: true },
  { _id: 'dm-015', name: 'Amlodipine 5', category: 'Cardiac', composition: 'Amlodipine', dosage: '1 tablet daily', batchNumber: 'AML5-K91', supplierName: 'Zydus', purchasePrice: 18, sellingPrice: 36, stockQuantity: 130, lowStockThreshold: 25, expiryDate: '2027-04-03', isPublicVisible: true, availabilityStatus: 'available', description: 'Blood pressure management', usageInstructions: 'Same time daily', isPrescriptionRequired: true },
  { _id: 'dm-016', name: 'Telmisartan 40', category: 'Cardiac', composition: 'Telmisartan', dosage: '1 tablet daily', batchNumber: 'TEL40-K19', supplierName: 'Aristo', purchasePrice: 34, sellingPrice: 62, stockQuantity: 7, lowStockThreshold: 12, expiryDate: '2026-05-10', isPublicVisible: true, availabilityStatus: 'available', description: 'Hypertension support', usageInstructions: 'Monitor BP regularly', isPrescriptionRequired: true },
  { _id: 'dm-017', name: 'Cough Syrup (DXM)', category: 'Respiratory', composition: 'Dextromethorphan', dosage: '10 ml twice daily', batchNumber: 'CSY-L77', supplierName: 'Benadryl Dist.', purchasePrice: 52, sellingPrice: 85, stockQuantity: 21, lowStockThreshold: 10, expiryDate: '2026-10-28', isPublicVisible: true, availabilityStatus: 'available', description: 'Dry cough relief', usageInstructions: 'Shake well before use', isPrescriptionRequired: false },
  { _id: 'dm-018', name: 'Saline Nasal Spray', category: 'Respiratory', composition: 'Sodium Chloride', dosage: '2 sprays each nostril', batchNumber: 'SNS-M14', supplierName: 'NasalCare India', purchasePrice: 44, sellingPrice: 79, stockQuantity: 0, lowStockThreshold: 8, expiryDate: '2026-09-12', isPublicVisible: true, availabilityStatus: 'out_of_stock', description: 'Nasal congestion relief', usageInstructions: 'Use as needed', isPrescriptionRequired: false },
  { _id: 'dm-019', name: 'Ibuprofen 400', category: 'Painkiller', composition: 'Ibuprofen', dosage: '1 tablet after meal', batchNumber: 'IBU400-N11', supplierName: 'Pfizer India', purchasePrice: 20, sellingPrice: 38, stockQuantity: 58, lowStockThreshold: 18, expiryDate: '2026-08-30', isPublicVisible: true, availabilityStatus: 'available', description: 'Pain and inflammation', usageInstructions: 'Avoid empty stomach', isPrescriptionRequired: false },
  { _id: 'dm-020', name: 'Diclofenac Gel', category: 'Painkiller', composition: 'Diclofenac', dosage: 'Apply thin layer 2-3 times', batchNumber: 'DCLG-O22', supplierName: 'Volini Supply Chain', purchasePrice: 46, sellingPrice: 82, stockQuantity: 19, lowStockThreshold: 10, expiryDate: '2026-06-01', isPublicVisible: true, availabilityStatus: 'available', description: 'Topical pain relief', usageInstructions: 'External use only', isPrescriptionRequired: false },
];

export const chemistDummyOrders = [
  { _id: 'ord-001', orderId: 'ORD-20260328001', patientName: 'Ravi Kumar', items: [{ medicineName: 'Paracetamol 650', quantity: 2 }], totalAmount: 72, paymentStatus: 'Paid', fulfillmentType: 'delivery', status: 'Delivered', prescriptionStatus: 'not_required', orderDate: new Date(Date.now() - 2 * 86400000).toISOString() },
  { _id: 'ord-002', orderId: 'ORD-20260328002', patientName: 'Asha Verma', items: [{ medicineName: 'Azithromycin 500', quantity: 1, prescriptionRequired: true }], totalAmount: 110, paymentStatus: 'Pending', fulfillmentType: 'pickup', status: 'Pending', prescriptionStatus: 'pending', prescriptionFileUrl: 'https://example.com/demo-rx.pdf', orderDate: new Date(Date.now() - 5 * 3600000).toISOString() },
  { _id: 'ord-003', orderId: 'ORD-20260328003', patientName: 'Nisha Singh', items: [{ medicineName: 'ORS Sachet', quantity: 4 }], totalAmount: 60, paymentStatus: 'Pending', fulfillmentType: 'delivery', status: 'Processing', prescriptionStatus: 'not_required', orderDate: new Date(Date.now() - 3600000).toISOString() },
  { _id: 'ord-004', orderId: 'ORD-20260328004', patientName: 'Imran Ali', items: [{ medicineName: 'Dolo 650', quantity: 1 }], totalAmount: 38, paymentStatus: 'Failed', fulfillmentType: 'delivery', status: 'Cancelled', prescriptionStatus: 'not_required', orderDate: new Date(Date.now() - 86400000).toISOString() },
];
